#!/usr/bin/env python
import subprocess
import os
import shlex
import sys
import tempfile

def run(cmd):
    return subprocess.check_output(shlex.split(cmd))[:-1]
filename = sys.argv[1]
if filename.endswith('.go'):
    if filename[0] != '/':
        filename = os.path.join(os.getcwd(), filename)

if 'GOPATH' in os.environ:
    base = os.path.join(os.environ['GOPATH'], 'src/')
else:
    os.exit(0)
# are we off the go path?
if base not in filename:
    package = filename
else:
    relative_filename = filename.replace(base,'')
    package = relative_filename.replace('/'+os.path.basename(relative_filename), '')
try:
    if 'test' in filename:
        subprocess.call(['timeoue', '5', 'go', 'test', package])
    else:
        #check for main files
        _, fname = tempfile.mkstemp()
        try:
            subprocess.call(['go', 'build','-o', fname, package])
        finally:
            os.remove(fname)
except:
    pass

