#!/usr/bin/env python
import subprocess
import os
import shlex
import sys
#just for debugging
with open('/tmp/foo', 'w') as f:
    f.write(str(sys.argv))
    f.write('\n')

def run(cmd):
    return subprocess.check_output(shlex.split(cmd))[:-1]
filename = sys.argv[1]
if filename.endswith('.go'):
    if filename[0] != '/':
        filename = os.path.join(os.getcwd(), filename)

base = os.path.join(os.environ['GOPATH'], 'src/')
relative_filename = filename.replace(base,'')
package = relative_filename.replace('/'+os.path.basename(relative_filename), '')

go = os.path.join(os.environ['GOROOT'], 'bin', 'go')
try:
    if filename.endswith('.proto'):
        filename = filename.replace(os.getcwd()+'/', '')
        subprocess.call(['protoc', '--go_out=.', filename])
    elif 'test' in filename:
        subprocess.call(['go', 'test', package])
    else:
        subprocess.call(['go', 'build', package])
except:
    pass
